export const products = [
  {
    id: "0",
    name: "vivo X90 Pro+",
    price: "1.450,00",
    brand: "Vivo",
    type: "smartphone",
    special: "bestsellers",
    image: "../assets/products/phone0.jpg",
  },
  {
    id: "1",
    name: "iQOO 11",
    price: "1.150,00",
    brand: "Vivo",
    type: "smartphone",
    special: "dailyoffer",
    image: "../assets/products/phone1.jpg",
  },
  {
    id: "2",
    name: "Legion Y70",
    price: "2.330,00",
    brand: "Lenovo",
    type: "smartphone",
    special: "bestsellers",
    image: "../assets/products/phone2.jpg",
  },
  {
    id: "3",
    name: "Redmi K50 Ultra",
    price: "1.800,00",
    brand: "Xiaomi",
    type: "smartphone",
    special: "normal",
    image: "../assets/products/phone3.jpeg",
  },
  {
    id: "4",
    name: "ASUS Zenfone 9",
    price: "1.700,00",
    brand: "Asus",
    type: "smartphone",
    special: "normal",
    image: "../assets/products/phone4.jpg",
  },
  {
    id: "5",
    name: "Xiaomi 12T Pro",
    price: "1.222,00",
    brand: "Xiaomi",
    type: "smartphone",
    special: "normal",
    image: "../assets/products/phone5.jpg",
  },
  {
    id: "6",
    name: "Red Magic 7",
    price: "1.990,00",
    brand: "Nubia",
    type: "smartphone",
    special: "normal",
    image: "../assets/products/phone6.jpg",
  },
  {
    id: "7",
    name: "Monitor BenQ ZOWIE",
    price: "1.990,00",
    brand: "BenQ",
    type: "monitor",
    special: "bestsellers",
    image: "../assets/products/monitor0.jpg",
  },
  {
    id: "8",
    name: "Monitor LG Full HD",
    price: "2.590,00",
    brand: "LG",
    type: "monitor",
    special: "normal",
    image: "../assets/products/monitor1.jpg",
  },
  {
    id: "9",
    name: "Monitor Dell Ultrasharp",
    price: "2.200,00",
    brand: "Dell",
    type: "monitor",
    special: "dailyoffer",
    image: "../assets/products/monitor2.jpg",
  },
  {
    id: "10",
    name: "AOC Hero 27",
    price: "2.150,00",
    brand: "AOC",
    type: "monitor",
    special: "normal",
    image: "../assets/products/monitor3.jpg",
  },
  {
    id: "11",
    name: "Monitor BenQ BL2420PT",
    price: "1.150,00",
    brand: "BenQ",
    type: "monitor",
    special: "normal",
    image: "../assets/products/monitor4.jpg",
  },
  {
    id: "12",
    name: "Monitor Acer 27",
    price: "2.150,00",
    brand: "Acer",
    type: "monitor",
    special: "bestsellers",
    image: "../assets/products/monitor5.jpg",
  },
  {
    id: "13",
    name: "GeForce RTX 4090",
    price: "7.150,00",
    brand: "Nvidia",
    type: "placa de video",
    special: "dailyoffer",
    image: "../assets/products/vga1.jpg",
  },
  {
    id: "14",
    name: "GeForce RTX 4080",
    price: "4.150,00",
    brand: "Nvidia",
    type: "placa de video",
    special: "normal",
    image: "../assets/products/vga2.jpg",
  },
  {
    id: "15",
    name: "GeForce RTX 4070 Ti",
    price: "3.180,00",
    brand: "Nvidia",
    type: "placa de video",
    special: "normal",
    image: "../assets/products/vga3.jpg",
  },
  {
    id: "16",
    name: "GeForce RTX 3090 Ti",
    price: "2.980,00",
    brand: "Nvidia",
    type: "placa de video",
    special: "dailyoffer",
    image: "../assets/products/vga4.jpg",
  },
  {
    id: "17",
    name: "Radeon RX 7900 XTX",
    price: "2.780,00",
    brand: "AMD",
    type: "placa de video",
    special: "normal",
    image: "../assets/products/vga5.jpg",
  },
];
